#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# --names test,lint,typecheck,build
# "yarn run test --watch=false" \
# "yarn run build" 
  # --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "lint,typecheck" \
    "yarn run lint" \
    "yarn run typecheck" \
