#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# --names test,lint,typecheck,build
# "yarn run test --watch=false" \
# "yarn run build" 

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "lint,typecheck" \
  --prefix-colors "bgRed.bold,bgGreen.bold,bgBlue.bold,bgMagenta.bold" \
    "yarn run lint" \
    "yarn run typecheck" \
